package com.daqsoft.itinerary.bean

/**站点信息*/
data class SiteInfoBean(
    val auditNum: Int,
    val betaStatus: Int,
    val companyCount: Int,
    val companyDomain: String,
    val companyName: String,
    val contact: String,
    val contactPhone: String,
    val createTime: String,
    val creditStatus: Int,
    val email: String,
    val emergencyPhone: String,
    val emergencyStatus: Int,
    val enableOutSite: Int,
    val english: String,
    val h5Domain: String,
    val id: Int,
    val name: String,
    val outsideLink: String,
    val outsideStatus: Int,
    val programDomain: String,
    val qrCode: String,
    val region: String,
    val regionName: String,
    val remark: String,
    val serviceRobot: Boolean,
    val shopCode: String,
    val shopName: String,
    val shopUrl: String,
    val siteCode: String,
    val siteIntroduce: String,
    val siteLanguage: String,
    val siteLogo: String,
    val sitePhone: String,
    val siteType: String,
    val siteVersion: String,
    val smsNum: Int,
    val status: Int,
    val tags: String,
    val totalAuditNum: Int,
    val totalNum: Int,
    val updateTime: String,
    val vipPlayStatus: Int
)