package com.daqsoft.provider.bean

/**
 * 乡村列表
 */
data class CountryListBean(
    var activityInfo: List<ActivityInfo>,
    var address: String,
    var audio: String,
    var briefing: String,
    var code: String,
    var contentDataList: List<ContentVoBean>,
    var id: Int,
    var images: String,
    var isCharge: Int,
    var latitude: Double,
    var longitude: Double,
    var name: String,
    var openTimeEnd: String,
    var openTimeStart: String,
    var panoramaUrl: String,
    var region: String,
    var regionName: String,
    var resourceCode: String,
    var spotsNum: Int,
    var srs: Int,
    var suggestedTime: String,
    var suggestedTimeHour: Int,
    var video: String,
    var vipResourceStatus: VipResourceStatus
)

data class ActivityInfo(
    var activityStatus: Int,
    var address: String,
    var cityRegionNames: String,
    var classifyId: Int,
    var classifyName: String,
    var coverImage: String,
    var createTime: String,
    var faithAuditStatus: Int,
    var faithAuditValue: Int,
    var faithUseStatus: Int,
    var faithUseValue: Int,
    var id: Int,
    var images: String,
    var integral: Int,
    var jumpName: String,
    var jumpType: String,
    var jumpUrl: String,
    var latitude: String,
    var lineFlag: Int,
    var liveUrl: String,
    var longitude: String,
    var method: String,
    var money: Double,
    var name: String,
    var orgId: Any,
    var recommendChannelHomePage: Int,
    var recommendHomePage: Int,
    var recruitedCount: Any,
    var region: String,
    var regionName: String,
    var regionNameStr: String,
    var remark: String,
    var resourceCount: Int,
    var resourceId: Int,
    var resourceNameStr: String,
    var signEndTime: String,
    var signStartTime: String,
    var siteId: Int,
    var sort: Any,
    var status: Int,
    var stock: Int,
    var tag: String,
    var tagNames: String,
    var teachUnit: String,
    var teamId: Any,
    var top: Int,
    var totalStock: Int,
    var type: String,
    var useEndTime: String,
    var useStartTime: String,
    var userHead: String,
    var userLevel: Any,
    var userName: String,
    var userResourceStatus: UserResourceStatus
)